FROM apache/airflow:2.10.5-python3.12

# Libs usadas pelo etl_tasks.py (bronze/silver/gold)
RUN pip install --no-cache-dir \
    pandas \
    numpy \
    sqlalchemy \
    psycopg2-binary \
    python-dotenv